on load:
	send "&7[&bTiny Real Drops&7] &8» &2Enabled" to console

on unload:
	send "&7[&bTiny Real Drops&7] &8» &cDisabled" to console

#
# These triggers fix some drops.
#

on break of glass:
	if gamemode of player is not creative:
		drop glass

on break of glass pane:
	if gamemode of player is not creative:
		drop glass pane

on break of bookshelf:
	if gamemode of player is not creative:
		cancel event
		set block to air
		drop bookshelf
