command /rename [<text>]:
    permission: rename.use
    description: Rename the item in your hand.
    trigger:
        if player's tool is not air:
            if arg-1 is set:
                set name of player's tool to colored arg-1
            else:
                message "&cYou need to describe the name for the object."
        else:
            message "&cYou need to have a specific item in your hand."